### ISSUE TITLE
Question - Playlist.json Converter

### ISSUE THREAD

**Issue by slade-cj** [cbz/tidal_export#1]
Hi - thanks for writing these utilities - as Tony the Tiger said - They're Great!

One question - I've tried a few different converters and as of yet have been unable to produce a readable result.  As such, I wanted to ask what conversion process you use or might suggest?  I've tried going to csv & text but problems arise. 
xml seems to work, but trying to convert that fails.

Thoughts?

Thanks,
Jason

**Comment by cbz** [comment]
Not sure what you mean by 'conversion process' ? If you just want to dump stuff out as json (for example), you can replace the db.insert call with a call to json dumps to dump out the playlist structure you created:

```
diff --git a/export.py b/export.py
index 09a24d5..7fa273d 100644
--- a/export.py
+++ b/export.py
@@ -2,6 +2,7 @@

 from tinydb import TinyDB
 import tidalapi
+import json

 DBASE="playlist.json"

@@ -26,7 +27,7 @@ for p in playlists:
         tracks.append({'artist': t.artist.name, 'album': t.album.name, 'track': t.name, 'id': t.id})

     playlist['tracks'] = tracks
-
-    db.insert(playlist)
+    print(json.dumps(playlist, indent=4))
+    #db.insert(playlist)

 db.close()

```

You can copy over additional attributes you need - the ones I used were those handy for my purpose (where for re-import I only really need the trackid, but for human use or export into another music service the track/album/artist is handy for a lookup).  The only reason I didn't use the structures the API gives me 'raw' was that they contained a lot of extraneous information and changed slightly over time.

**Comment by slade-cj** [comment]
Thank you for your reply.  My goal was to upload a csv or xml version of my Tidal playlists to another service, but I was having no luck in the conversion from json to csv and although the conversion to xml appeared to be successful, the upload of the xml file failed.

Thank you for the diff report.  Although I'm not (yet) familiar with that syntax, I'm working on that as well as reading up on the tidalapi and tinydb.

**Comment by cbz** [comment]
tinydb is just the intermediate repository between the export and import scripts. If you need xml output you should just print that out and redirect to file.

That said, what tool are you trying to import it into? Most of them require particular formats of XML with particular fields filled in it particular ways - similarly with CSV imports, you'll need particular fields in a particular order .  If you can give me an indication I might be able to help you a little more.

**Comment by slade-cj** [comment]
Thanks, I'll give printing to file a go.

The service that I tried uploading the xml to was only a test.  Later this year, HDTracks will be launching a subscription service with MQA content as a result of their partnering with Lenbrook who bought MQA Labs and it's that service I'll be wanting to upload my Tidal playlist to.

**Comment by cbz** [comment]
> The service that I tried uploading the xml to was only a test.

So which test service is it and what is the documentation on it?  As I said, not all xml files are created equal, and no service will be able to infer from an arbitrary file.  One of the more common ones is that of itunes playlists.

**Comment by slade-cj** [comment]
It was Amazon Music where the xml upload had failed.

**Comment by cbz** [comment]
Right, and that's available via 3rd party services like TuneMyMusic (which they partner with) and others like Soundiiz.  In both cases what they are looking for seems to be iTunes format files - the easiest way to see how they are constructed is to export a sample library via the iTunes app and look at the result - it's not particularly XMLish XML - a lot of things that would normally be tags are expressed as key/value pairs.

Although most of these services have the ability to export their own XML format instead (from the music service of your choice), so in this case I'm not sure why you would not start off using that - you won't be able to do an import until you know what format MQALabs expects anyway.
